### ISSUE TITLE
Search and result aggregations with @searchable directive

### ISSUE THREAD

**Issue by da45** [aws-amplify/amplify-category-api#1101]
### Amplify CLI Version

10.5.0

### Question

Hi,
This is a Usage Question, there is no issue right now, but I have ambiguity with @searchable directive,
As you may know,  AppSync is good for simple filtering, but searching for data using advanced filters becomes not possible, like sum, average, min, max, regex, total search result count queries 

question 1: does add @searchable directive will launch an EC2 instance (or OpenSearch instance) automatically and start invoicing even in idle time without invoking any query?
question 2: for simple queries, is it possible to not use opensearch, and how to tell aws amplify to use AppSync instead for data filtering (without remove of @searchable)?
question 3:  Do you think using a custom business logic with Lambda function for advanced filters is better than OpenSearch for small-budget projects?

Hope I was clear
Thanks

**Comment by josefaidt** [comment]
Hey @da45 :wave: thanks for raising this! For what it's worth I also think this is a great question to ask in our [community Discord server](https://discord.gg/invite/amplify). To answer your questions:

> question 1: does add https://github.com/searchable?type=source directive will launch an EC2 instance (or OpenSearch instance) automatically and start invoicing even in idle time without invoking any query?

Yes

> question 2: for simple queries, is it possible to not use opensearch, and how to tell aws amplify to use AppSync instead for data filtering (without remove of https://github.com/searchable?type=source)?

No, AppSync does not perform data filtering, however you can use filters with `list*` queries, or create a GSI to query on specific indexes

> question 3: Do you think using a custom business logic with Lambda function for advanced filters is better than OpenSearch for small-budget projects?

To answer this effectively, what sort of custom business logic are you looking to apply?

**Comment by da45** [comment]
thank you @josefaidt, 
I want to add that there are mainly three pricing models in OpenSearch: On-Demand, Reserved, and Serverless, 
regarding the third pricing model (serverless), it is mentioned in the official doc that we can  only pay for the resources consumed by the workload, 
As I understand from your answer above, it is not possible today to go with Amazon OpenSearch Serverless pricing model,
Hope this will be adopted as an improvement in future

**Comment by davisengeler** [comment]
Any news for OpenSearch Serverless support?

**Comment by hackmajoris** [comment]
@josefaidt  I'll go forward with asking related question to the @searchable functionality.

Our case:
We use @searchable in order to perform filtering on some indexes. The problem is that we have 5 developers + 3 environments, making a total of 8 environments that are always up. It can increase to 15-20 environments due to feature branches and preview environments. The cost at the end of the month becomes huge because of the OpenSearch instances, which we don't even use, except for production environments.

It would be very helpful to have an option to reuse the same OpenSearch instance for each environment by having multiple indexes per environment. Is it possible, or is the overhead required not worth it?

**Comment by redjonzaci** [comment]
Any update on this?
