### ISSUE TITLE
GRAPHQL 1 to 1 relation @hasOne and @belongsTo are not related to each other.

### ISSUE THREAD

**Issue by vincent38wargnier** [aws-amplify/amplify-category-api#1184]
Hi,
the example in the doc is not working for me, i get those results after setting those tables : 
```
type Individual @model {
  id: ID!
  homeAddress: Address @hasOne
  shippingAddress: Address @hasOne
}

type Address @model {
  id: ID!
  homeIndividualID: ID
  shippingIndividualID: ID
  homeIndividual: Individual @belongsTo(fields: ["homeIndividualID"])
  shipIndividual: Individual @belongsTo(fields: ["shippingIndividualID"])
}
```

Requests : 
```
mutation MyMutation {
  createIndividual(input: {id: "i1"}) {
    id
  }
}

mutation MyMutation2 {
  createAddress(input: {homeIndividualID: "i1", id: "a1"}) {
    id
    homeIndividual {
      id
      homeAddress {
        id
      }
    }
  }
}

```

Résult : 
```
{
  "data": {
    "createAddress": {
      "id": "a1",
      "homeIndividual": {
        "id": "i1",
        "homeAddress": null
      }
    }
  }
}
```

So here the @hasOne and @belongsTo are not related to each other. I tried with the Amplify mock and AWS AppSync and I get the same issue.

HELP

_Originally posted by @vincent38wargnier in https://github.com/aws-amplify/amplify-cli/issues/556#issuecomment-1397726729_

**Comment by AnilMaktala** [comment]
Hey @vincent38wargnier 👋 , Thank you for raising the issue. Can you please run the getIndividual(id: "i1") and let me know the results.

**Comment by vincent38wargnier** [comment]
Hi @AnilMaktala, as we can see in my previous message the result is he same if I request the individual id: "i1" : 
```
{
    "id": "i1",
    "homeAddress": null
}
```

**Comment by marcvberg** [comment]
Hi @vincent38wargnier ,

There is not currently a workaround for this, because `@hasOne` is not able to specify which field in the target model is used for the connection, there's no way for the transformer to disambiguate which is which. You may have better luck if you adjust your modeling pattern to be able to fit the objects into one `@hasMany`, or use some manual relationship management in your source code

**Comment by vincent38wargnier** [comment]
Hi @marcvberg ,
thank you for your reply. That's what I decided to do to une hasMany, but then I was wondering what was the meaning in [the documentation](https://docs.amplify.aws/cli/graphql/data-modeling/#modify-subscriptions-real-time-updates-access-level) to propose this type of relationship.
![image](https://user-images.githubusercontent.com/33725800/216442055-ab0e8d21-17b9-4973-af6b-38551cba4060.png)

In the documentation it says that hasOne and hasMany are working in the same way :
![image](https://user-images.githubusercontent.com/33725800/216442282-d87626db-8e22-4f1b-8524-5d8a280b2a99.png)

So that's why I was expecting to see the parent "homeAddress" in the "homeAddress" child of the "Individual" table as used in their example.

Or did I miss understand and this phrase explains what you just meant?
![image](https://user-images.githubusercontent.com/33725800/216442810-e6617e91-618f-4fc7-865d-971e7446b9c2.png)

Thank you.

**Comment by marcvberg** [comment]
That might just be an error in the documentation, I'm not able to at the moment but I will make a note to follow up on this

**Comment by marcvberg** [comment]
@vincent38wargnier I tested this

The relationships work, but you need to populate the id field for the Address you created into the relevant field in the Individual. You're able to get the relationship from the Address to the Individual because it's using the field you just defined by creating the Address, but you haven't saved the id of the Address in the Individual yet through an update mutation.
