### ISSUE TITLE
Is it possible to set auth rule for manyToMany relations?

### ISSUE THREAD

**Issue by safal07** [aws-amplify/amplify-category-api#1193]
### Amplify CLI Version

10.6.1

### Question

Given this relationship, ` roles: [Role] @manyToMany(relationName: "ContributionRole")`, a model named ContributionRole is auto-generated without @auth directive. My app requires a private auth directive for all models. Is there a way to specify auth directive while declaring manyToMany relationship?

**Comment by AnilMaktala** [comment]
Hi @safal07, Thank you for raising the question. The issue can't be reproduced with the steps listed [here](https://docs.amplify.aws/cli/graphql/data-modeling/#many-to-many-relationship). Can you kindly give us more details, such as the Schema file and the name of the file where the issue is observed?

**Comment by chrisbonifacio** [comment]
Hi 👋 Closing this as we have not heard back from you. If you are still experiencing this issue and in need of assistance, please feel free to comment and provide us with any information previously requested by our team members so we can re-open this issue and be better able to assist you.

Thank you!
