### ISSUE TITLE
Use child table primary key hash as @hasMany key in parent table

### ISSUE THREAD

**Issue by unknown1337** [aws-amplify/amplify-category-api#1310]
### Amplify CLI Version

10.7.2

### Question

How can I using the model below create a hasmany relation from Alpha to Bravo without introducing new fields/ keys on Bravo? I find this challenging as the Bravo model has no LSI/ GSI keys defined that I can reference in the @hasmany composable. I need no LSI/ GSI  as I will query the Bravo table using only the Alpha2 key.
```
type Alpha @model {
    AlphaId: ID! @primaryKey
    label: String
    Bravos: [Bravo] @hasMany
}

type Bravo @model {
    AlphaId2: ID! @primaryKey(sortKeyFields: ["BravoId"])
    BravoId: ID!
    label: String
}
```
THANKS!

**Comment by marcvberg** [comment]
Hi @unknown1337,

There's not a way to do this currently, the way `@hasMany` works it needs to create/use a separate field in the child model to store the key from the parent. If you were to use the primary key field of the child model, it would break for a couple reasons

1) The `@hasMany` relationship doesn't allow you to define the field in the target child model
2) You could do it with a `@belongsTo`, but this would break the primary key contract because it would try to store the parent key from `Alpha` in the primary key for `Bravo`.

Is there another specific problem you're trying to solve that we might be able to help with? You won't be able to escape the need for an additional index for this, it's part of the relational logic and it will create the index if you don't explicitly define one

**Comment by unknown1337** [comment]
Hmm, thinking of a more concrete example Post -> comments relation I've got two options to retreive all comments for a given post:
A. relational query with extra GSI on Comment table
```
type Post @model {
  id: ID!
  title: String!
  comments: [Comment] @hasMany
}

type Comment @model {
  id: ID!
  content: String!
}
```
Or B. no 'Amplify relation' but included the postId in the primary key. Getting all Comments for a post is possible but might need  two consecutive queries.
```
type Post @model {
  id: ID!
  title: String!
}

type Comment @model {
  postId: !ID  @primaryKey(sortKeyFields: ["id"])
  id: ID!
  content: String!
}
```

What is best, and why? THANKS @marcvberg

**Comment by phani-srikar** [comment]
Hi @unknown1337, thanks for raising this and putting together the pros and cons for both approaches. To re-state @marcvberg 's comment, option B is not a feasible option currently and we would recommend going with option A.
About the `read cost` that you brought up, there will be a single query that uses the join GSI to fetch the `comments` attached to a post. 
Option B that you've mentioned is not ideal since it requires you to specify the `postID` in order to query a comment which shouldn't be required.

**Comment by unknown1337** [comment]
Thanks, clear!
