### ISSUE TITLE
Error when defining a @hasMany relationship with an interface in AWS Amplify GraphQL schema

### ISSUE THREAD

**Issue by Mr-Raian** [aws-amplify/amplify-category-api#1322]
### Amplify CLI Version

10.8.1

### Question

I have this simple schema:
```graphql
type Student @model {
  username: String!
  firstName: String!
  lastName: String!
  chats: [Chat] @hasMany
}

type Teacher @model {
  username: String!
  firstName: String!
  lastName: String!
  chats: [Chat] @hasMany
}

union User = Student | Teacher

type Chat @model {
  users: [User!]! @hasMany
  messages: [Message] @hasMany
}

type Message @model {
  sender: User! @hasOne
  content: String!
  chat: Chat! @belongsTo
  createdAt: AWSDateTime!
}
```
When I do `amplify push` I get this error:
```
🛑 Could not find related type with name User while processing relationships.
```
Could anyone help me figure out what's wrong with the schema? It all looks good to me
I've googled it and it seems to be related to having a `@hasMany`relation with an interface, like this:
```graphql
  users: [User!]! @hasMany
```

**Comment by Bhavika-Gianey** [comment]
Hello @Mr-Raian, currently, Amplify does not support schemas with unions, and you cannot use relationships with them. This is because unions do not have a key or primary index, and they do not generate a DynamoDB table as the Student or Teacher schema does.

To account for multiple users such as Students and Teachers in your schema, you could consider using other types such as an enum type. This would allow you to rewrite your schema in a way that can be compiled successfully with Amplify.
 ```
enum USER_TYPE {
  STUDENT
  TEACHER
}

type User @model {
  username: String!
  firstName: String!
  lastName: String!
  type: USER_TYPE!
  chats: [Chat] @hasMany
}

type Chat @model {
  users: [User!]! @hasMany
  messages: [Message] @hasMany
}

type Message @model {
  sender: User! @hasOne
  content: String!
  chat Chat! @belongsTo
  createdAt: AWSDateTime!
}
```
