### ISSUE TITLE
When creating a hasMany and using an index the corresponding belongsTo returns null

### ISSUE THREAD

**Issue by capitaldotcodes** [aws-amplify/amplify-category-api#1488]
### How did you install the Amplify CLI?

npm

### Amplify CLI Version

12.0.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No

### Describe the bug

I created a has many using an index
` geoTypes: [GeoType] @hasMany(indexName: "byCategory", fields: ["value"])`

I also created a belongs to on the corresponding field

 `categoryModel: Category @belongsTo( fields: ["category"])`

Requesting the category model works fine as the vtl is correctly configured to handle the index

Requesting the HasOne model returns null

It is easy enough to get around by creating an index and updating the corresponding vtl.

Unfortunately the original vtl assumes that you are using the id of the model and thus uses the wrong index returning a null value

All the field functionality works as expected though so its not so bad but I am sure that DataStore will choke to death with it.

### Expected behavior

Creating a belongsTo on a model should query the right index. Especially if you go to all the effort of creating one to find it doesn't work. 

### Reproduction steps

Create has @hasMany with an index from ModelB on ModelA with relevant fields
Create a @belongsTo with relevant fields on ModelB
Request ModelB look for null value 
Create relevant index on ModelA 
Look at relevant vtl file and update with correct index and key
Appreciate the success.

### Log output

<details>

```
# Put your logs below this line


```

</details>

### Before submitting, please confirm:

- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

**Comment by AnilMaktala** [comment]
Hey @capitaldotcodes, Thank you for raising this. After attempting to reproduce the issue based on the steps provided in the description, we were unable to reproduce the problem. In order to assist you further, could you kindly provide us with detailed steps to reproduce the issue? This will enable us to investigate and address the problem more effectively.

Schema used:
```
type Post @model @auth(rules: [{allow: public}]){
  postId: ID! @primaryKey(sortKeyFields:["title"])
  title: String!
  comments: [Comment] @hasMany(indexName:"byPost", fields:["postId", "title"])
}

type Comment @model @auth(rules: [{allow: public}]){
  commentId: ID! @primaryKey(sortKeyFields:["content"])
  content: String!
  post: Post @belongsTo(fields:["postId", "postTitle"])
  postId: ID @index(name: "byPost", sortKeyFields:["postTitle"]) # customized foreign key for parent primary key
  postTitle: String # customized foreign key for parent sort key
}
```
We are able to see the expected results, please see the screenshots below.

<img width="997" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/f0d0c4a9-6933-4be6-adc9-61760d87565f">

<img width="1037" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/b473baf2-0017-4fd8-8176-bf315116ea8f">
<img width="1045" alt="image" src="https://github.com/aws-amplify/amplify-category-api/assets/3206171/1a088b42-2dd7-446c-9dc5-f09f5a5b9be7">

**Comment by capitaldotcodes** [comment]
I came to this realisation pretty much after I posted it. Explicitly using the @primaryKey directive makes it clear what is going on behind the scenes. The limitation then becomes only allowing one @primaryKey and therefore Dynamo would not be able to ensure it returned a single entity on the @belongsTo connection. If there is anything you can add about using GSI/ an example I'd really appreciate it. Feel free to close the ticket out I am satisfied it is working as expected.
