### ISSUE TITLE
Amplify push failed: Waiting for DynamoDB indices to be ready.

### ISSUE THREAD

**Issue by atef-abdellatif** [aws-amplify/amplify-category-api#1505]
Hey,

Amplify push failed after I changed the primary key of a table in the graphql schema. 
Error: table name should be passed.
The deployment hung for a few minutes with the following message displayed in the console: 
Waiting for⠦ Waiting for DynamoDB indices to be ready.

Project Identifier: fa62b31536a55f4721b023a1da51ce62

**Comment by AnilMaktala** [comment]
Hi @atef-abdellatif, Thank you for raising this issue. Please attempt the following instructions and inform us if they resolve your issue:

1. Delete the table's primaryKey and execute `amplify push`.
2. Include the primaryKey as a new property and execute `amplify push`.
3. Please carry out this action for one table at a time.

**Comment by atef-abdellatif** [comment]
Hey Anil,

thanks for getting back to me! I actually tried what you suggested and I even deleted the table all together and cleared my browser's history restarted my machine but unfortunately nothing worked. I kept getting this message: 
 A deployment is in progress.
🛑 If the prior rollback was aborted, run:
🛑 "amplify push --iterative-rollback" to rollback the prior deployment
🛑 "amplify push --force" to re-deploy

I tried the two commands mentioned above one at a time but again nothing worked! 

Atef

**Comment by AnilMaktala** [comment]
Hi @atef-abdellatif, sorry to hear that the suggested workaround didn't work. To resolve the deployment state error, please delete the deployment-state.json file from the S3 bucket. Then, try running `amplify push` again using your original schema.

**Comment by atef-abdellatif** [comment]
Hey Anil,

Thanks. I went ahead and deleted the deployment-state.json file and ran amplify push and it deployed the backend successfully. However, I still have the same problem with the table of question. I deleted it before running amplify push to make sure it's not gone cause any errors and after the deployment was successfully processed I re-added it to the schema file and re-ran amplify push, but got this error: 

The following resources failed to deploy:
Resource Name: AttractionIAMRole***(AWS::IAM::Role)
Event Type: create
Reason: AttractionIAMRole***-dev already exists

🛑 Resource is not in the state stackUpdateComplete
Name: AttractionIAMRole***(AWS::IAM::Role), Event Type: create, Reason: AttractionIAMRole***-dev already exists, IsCustomResource: false

--- end of error

**Comment by atef-abdellatif** [comment]
note: the table doesn't exist in DynamoDB tables

**Comment by atef-abdellatif** [comment]
Hi Anil,

I renamed the model and now everything is working as expected. Thanks. I dug a bit deeper into this issue and I think the reason the aeration model was throwing issues is that it still exists in the cloudFormation stack.  Is there a way to maybe delete the deleted resources from cloudFormation? Is it even a good idea to permanently delete the deleted resources from the cloudFormation?

**Comment by alharris-at** [comment]
Hi @atef-abdellatif - it is generally recommended that you don't manually (either via the AWS SDK or AWS Console) modify resources which are managed by a cloudformation stack, since these actions will necessarily induce `drift` on your stack. Certain resources allow for drift detection, but not all allow for importing these changes, and a subsequent `amplify push` will push those resource definitions BACK into Cloudformation, and they'll be correctly recreated.

The primary challenge w/ this though is that the steps and possibility of correcting this state is particularly dependent on the type of resource, and the shape of you app (what depends on it, etc.) so there's no great one-size-fits-all solution here.

In terms of correcting the stack, there are some steps for managing stack drift here - https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resource-import-resolve-drift.html#resource-import-resolve-drift-console, and a re:Post link on how to potentially mitigate the manual deletion - https://repost.aws/knowledge-center/failing-stack-updates-deleted

I hope that provides a little bit more context on how cloudformation stacks can be managed w/ manually drifted resources, and helps you get unblocked. Feel free to reopen this issue if you would like additional support!
