### ISSUE TITLE
How to update OpenSearch text analyzer?

### ISSUE THREAD

**Issue by redjonzaci** [aws-amplify/amplify-category-api#1717]
Is there any other workaround available for this except for manually creating the index with a non-default analyzer?

_Originally posted by @redjonzaci in https://github.com/aws-amplify/amplify-cli/issues/9588#issuecomment-1647471377_

**Comment by redjonzaci** [comment]
Thanks @josefaidt! Is there any update?

**Comment by alharris-at** [comment]
Hi @redjonzaci - As far as I'm aware, nothing has changed since the answer provided by Colin in the original linked ticket. I wouldn't recommend overriding the streaming lambda unless you're also going to override the search resolver as well (since any sort of token manipulation you perform in one you'll probably need to ensure you perform on searches as well).

Unfortunately, we don't offer any particular customization on that capability today, so I think manual creation would be the only straightforward route available.
