### ISSUE TITLE
Amplify Modeling Friendships

### ISSUE THREAD

**Issue by oyangjo** [aws-amplify/amplify-category-api#2172]
### Amplify CLI Version

12.8.2

### Question

Happy New Year!

I am creating a social application in which each user will have friends. I was wondering if there is a suggested way of creating a friendship structure using GraphQL. I found some links but mostly are open-ended:
- https://github.com/aws-amplify/amplify-cli/issues/1637
- https://stackoverflow.com/questions/65303170/modelling-friendship-with-aws-amplify

```
type User 
  @model 
  @auth(
    rules: [
      { allow: public, provider: apiKey, operations: [create, read, update]  },
      { allow: owner } 
    ]
  ) {
  id: ID!
  username: String!
  email: String!
  profilePictureUrl: String
  friendship: Friendship @hasOne
}

type Friendship 
  @model 
  @auth(
    rules: [
      { allow: public, provider: apiKey, operations: [create, read, update]  },
      { allow: owner }
      ]
  ) {
  id: ID!
  user: User @belongsTo
  friends: [String]
  outgoingFriendRequests: [String]
  incomingFriendRequests: [String]
}
```
In my case, there are a few issues:
- I won't be able to access User `profilePictureUrl` in S3, since the URL path is owner-based, such as `application_name/private/us-east-2:user_id`
- When I send a friend request, I will need to update my own `outgoingFriendRequests` and the potential friend's `incomingFriendRequests`
- Lastly, will this create a security risk? Since friendship schema is now public, anyone can edit other people's `friends` schema. In other words, you will be able to be friends with anyone before requesting.

**Comment by dpilch** [comment]
1. You can use field level auth to change authorization rules for profilePictureUrl: https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/customize-authorization-rules/#field-level-authorization-rules
2. You can use custom resolvers that perform custom mutations to the records: https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/custom-business-logic/. Alternatively you can use field level to give update rights to other users for `incomingFriendRequests` (probably not a good idea though because a user could remove other `incomingFriendRequests`.
3. Yes, but using the custom resolvers should allow you to restrict the authorization rules to remove this security concern.

**Comment by oyangjo** [comment]
1. That's a good idea
2. Thanks for the suggestion
3. Yes. It seems like [implementing a lambda](https://docs.amplify.aws/javascript/build-a-backend/graphqlapi/customize-authorization-rules/#custom-authorization-rule:~:text=groups%20per%20record-,Custom%20authorization%20rule,-You%20can%20define) is the way to do it.  

Regarding number 3, if I don't expose the functionality of editing the schema in the frontend, would it still consider a security risk?

**Comment by dpilch** [comment]
It will not be a security risk if you configure the auth rules and custom resolver logic properly.

**Comment by chrisbonifacio** [comment]
Closing this issue as it seems to be a question that was answered. If you run into any specific errors or bugs, please open a new issue. Otherwise, for general advice on architecture please consider asking such questions on the [Amplify Discord Server](https://discord.com/invite/amplify) where Amplify staff and community members can help provide guidance.
