### ISSUE TITLE
Automatically Generated GSI is not usable in app

### ISSUE THREAD

**Issue by MattWlodarski** [aws-amplify/amplify-category-api#2600]
### Environment information

```plain text
System:
  OS: macOS 14.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 20.45 MB / 16.00 GB
  Shell: /bin/zsh
Binaries:
  Node: 16.20.2 - /usr/local/bin/node
  Yarn: undefined - undefined
  npm: 8.19.4 - /usr/local/bin/npm
  pnpm: undefined - undefined
NPM Packages:
  @aws-amplify/backend: 1.0.2
  @aws-amplify/backend-cli: 1.0.3
  aws-amplify: 6.3.1
  aws-cdk: 2.141.0
  aws-cdk-lib: 2.141.0
  typescript: 5.3.3

AWS environment variables:
  AWS_STS_REGIONAL_ENDPOINTS = regional
  AWS_NODEJS_CONNECTION_REUSE_ENABLED = 1
  AWS_SDK_LOAD_CONFIG = 1
```

### Description

Often times when creating a relationship between two models, Amplify will automatically generate a GSI. However, you cannot use this GSI in queries in your app, so you need to create another one with the same primary key using .secondaryIndexes(). I feel like this is a waste and there should be a way to use the autogenerated GSI as a query in your code. Also, there is no way to set a sort key on the autogenerated GSI.

In Gen 1, you could create uni-directional relationships with the @key directive so this wasn't a problem. But Gen 2 forces bi-directional relationships which lead to the autogeneration of the GSI.

**Comment by AnilMaktala** [comment]
Hey @MattWlodarski, This seems to be a duplicate of #2601. Please subscribe to #2601 for future updates.

**Comment by metuuu** [comment]
I believe this is a separate issue than the #2601. They might relate to each other and the other issue might block this on or might not, but both of these are issues that should be discussed separately.

We currently have to have double GSI:s in our project due to this issue and we are already planning to drop using Amplify's 1-to-many relations completely due to there being no filtering and pagination support for them.

I see a lot of potential in Amplify Gen 2 but it is shame that it feels that Amplify just fails to properly support real world applications. I believe these kind of design issues are why Amplify isn't used that much. It really doesn't show bright future when there are so many old dead issues about real issues of Amplify.
