### ISSUE TITLE
Provide a way to add files to the CodegenAssets class.

### ISSUE THREAD

**Issue by ricardoribas** [aws-amplify/amplify-category-api#2901]
### Describe the feature you'd like to request

Right now, when you provision the AmplifyGraphqlApi, you are not capable of files to the CodegenAssets class. A schema metadata file is the only file uploaded. It would interesting to allow to configure `ISource`  resources to be uploaded as well. In my use case, I want to upload generated ts files so other repositories can retrieve those files. For instance, the generated queries, mutations and subscriptions. Also the TS types.

At the moment I have a total of two S3 buckets cause I cannot manipulate the existing codegen resource.

### Describe the solution you'd like

A codegenasset object property to the constructor in which you can send `ISource` (for instance you can pass a `Source.asset(testFolder)` with different files.

### Describe alternatives you've considered

There is no much to add here. The feature seems to be simple. Would be helpful some feedback.

### Is this something that you'd be interested in working on?

- [X] 👋 I may be able to implement this feature request

### Would this feature include a breaking change?

- [ ] ⚠️ This feature might incur a breaking change

**Comment by AnilMaktala** [comment]
Hi @ricardoribas, Thank you for bringing this up. The current behavior is intentional and designed this way to restrict the upload of other files into this S3 bucket. The workaround you’re using is the recommended approach for your requirements. If you have any specific needs or additional questions, please feel free to reach out, and we’ll be happy to help.
