### ISSUE TITLE
@auth on the GSIs mentioned in the @key 

### ISSUE THREAD

**Issue by arkllc** [aws-amplify/amplify-category-api#339]
**Is your feature request related to a problem? Please describe.**
Please allow the ability to add @auth on GSIs mentioned in @key

**Describe the solution you'd like**
in the GSIs mentioned in @key it would be great if adding @auth is allowed 

**Describe alternatives you've considered**
Adding field level auth is a choice but it fails to achieve 2 items:
1. If I would like to make 2-3 fields in a given table as public to everyone who is authenticated via Cognito pool then I need to add @auth on every necessary field. This adds unnecessary code. 
2. Also if I want to make these 2-3 fields more open than the @auth mentioned at the table level then it does not work. the additional @auth at field level can enable only more restrictive items but not less restrictive options.

**Comment by AnilMaktala** [comment]
Hi @arkllc 👋, We apologize for the delay in our response. This feature was requested before the GraphQL v2 version, and since then, several improvements have been made. In GraphQL v2, authorization rules now follow a denial-by-default approach. 
For more information on the Auth, please refer to this link: https://docs.amplify.aws/cli/graphql/authorization-rules/. These improvements may not address all of your use cases, but they certainly provide more options.

To migrate from GraphQL v1 to v2, please follow the instructions here: https://docs.amplify.aws/cli/migration/transformer-migration/#changes-that-amplify-cli-will-auto-migrate-for-you. 

We encourage you to try using the v2 version and let us know if it meets your needs.
We may give higher priority to this feature in the future if we receive more requests for it.
