### ISSUE TITLE
True multi-tenant support and modelling with @auth

### ISSUE THREAD

**Issue by jexh** [aws-amplify/amplify-category-api#452]
I have tried modelling my application with Amplify but, as far as I can see, the auth config using Cognito  does not currently support true multi-tenancy. By true multi-tenancy I mean that users belong to one or more organisations with a particular session being bound to a single organisation at a time. Data associated with one organisation should never be visible to another organisation. Like users, organisations need to be added or removed without infrastructure changes.

**Comment by BBopanna** [comment]
What is the time line on this ? this issue is open from 2018 ? Do you all need another 5 years ? Project managers - any sense of urgency around this ticket which is open from 2018 ? Disappointed! @abdallahshaban557 reopen https://github.com/aws-amplify/amplify-js/issues/10190

**Comment by BBopanna** [comment]
Copy-pasting the content of https://github.com/aws-amplify/amplify-js/issues/10190 here as advised by @abdallahshaban557 to carry on with the discussion here.


_Contents from https://github.com/aws-amplify/amplify-js/issues/10190 :_


Requirement - Implement multi tenancy in a react app backed by amplify ( Cognito + Appsync + S3)

1. Cognito is used for authentication 
2. Appsync for Graphql with DynamoDB
3. S3 storage to store images and videos

Use case and our idea with gaps - 

Use case -

1. Admin user should be able to sign up with CRUD access
2. Admin user should be able to add manager user with CRU access
3. Admin user should be able to add user with R access
4. Users of a company/tenancy should have access to only their Company/Tenancy data - Red company users should NOT have access to Blue Company data, do within their Company/Tenancy, based on their authorization access their access to their company data should be regulated.
5. Same logic needed for images and videos stored in S3.

**_Our attempted idea with gaps - which need help with OR a better design advise please :_**
 
_Graphql models : _

`============
type Post @model 
@auth(rules: [
  { allow: groups, groupsField: "adminGroup" , operations: [read, create, update, delete], provider: userPools}
  { allow: groups, groupsField: "managerGroup" , operations: [read, create, update], provider: userPools}
  { allow: groups, groupsField: "userGroup" , operations: [read], provider: userPools}
]) 
{
  id: ID!

  title: String
  
  adminGroup: String 
  @auth(rules: [{ allow: groups, groupsField: "adminGroup"}])
  
  managerGroup: String 
  @auth(rules: [{ allow: groups, groupsField: "adminGroup"},{ allow: groups, groupsField: "managerGroup"}])
  
  userGroup: String
}

type AuthorizationGroups @model 
@auth(rules: [
 { allow: private, operations: [read, create, update, delete], provider: iam }
]) 
{
  id: ID!

  tentantId: String!
  
  adminGroupId: String!
  
  managerGroupId: String!
  
  userGroupId: String!
}
============
`

_Flow :_

1. Admin will signup with the app 
2. We call post signup lambda hook to 
     a.  Add tenantId to user in cognito - uuid generated and put into cognito custom attribute - tenantId
     b.  Put an entry to AuthorizationGroups table with tentantId generated above from #a and uuids generated for adminGroupId, managerGroupId, userGroupId - this entity can only be operated by lambda hence the rule allow private. We do not want any direct user meddling or attempting to hack
3. Admin/Manager can create/updatePost record - during which we want to read the values for adminGroupId, managerGroupId and userGroupId from AuthorizationGroups entity for the tenantId of the belonging user, from cognito custom attribute- tenantId, and set these values before persisting - How can we achieve this ? Do not want to do it in client code - can be hacked is what we worry. Next lambda - How can the request be intercepted and these values set ? Unless all graphql APIs be explicitly routed to lambda which updates these values and then calls underLying AppSync APIs - too cumbersome and lot of hand written code ? Deal with resolver - again touch _all_ resolvers - very painful? Is there a better approach - a lambda hook that gets called for all AppSync calls where we set these values ?

4. Admin/Manager/User should be able to read the data, so again we need to use similar logic as from # 3 to proceed
5. How do we extend these for storage and retrieval of multimedia - Images, Videos from S3 ?

This - https://aws.amazon.com/blogs/mobile/appsync-lambda-auth/ seems like what we want but not able to put everything together for our use case.

Here is 2018 request for multi tenancy - https://github.com/aws-amplify/amplify-category-api/issues/449 which is not considered yet.

### Expected behavior

Possible options to implement multi tenancy.

**Comment by josefaidt** [comment]
closing as a duplicate of https://github.com/aws-amplify/amplify-category-api/issues/449

**Comment by AstralBaby** [comment]
As of today, its still not resolved. What a disappointment for people who invested time in this technology. So much hype for the amount of limitations around it....
