### ISSUE TITLE
Creating unnecessary and new OpenSearch domains on failed amplify push commands

### ISSUE THREAD

**Issue by VicFrolov** [aws-amplify/amplify-category-api#637]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

v14.18.2

### Amplify CLI Version

8.3.0

### What operating system are you using?

Mac

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

When upgrading from v1 to v2, I had a couple of failed `amplify push` runs. After resolving them all, and testing out functionality, everything was working, however in AWS OpenSearch console, I noticed new domains were created, now having a total of 4 for only 2 environments. A few weeks later, a few more pushes failed, and I now have 7 domains, when I should only have 2.

Can I safely manually delete these? Concerned this might keep happening, and then pointing to the newly created OpenSearch domains, as opposed to the old ones, requiring backfilling data. Also concerned about this happening in the background, and being charged for unused domains.

_Only have 2 environments (those with populated data), with 5 unnecessary additions/duplicates_
<img width="1082" alt="Screen Shot 2022-07-07 at 5 56 42 PM" src="https://user-images.githubusercontent.com/8305711/177895204-c37bd56e-6d4e-4952-9c08-88942c470698.png">

### Expected behavior

No unnecessary OpenSearch domains are generated

### Reproduction steps

Not sure how to repro

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line


```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ykethan** [comment]
Hello @VicFrolov, thank you for reaching out. I understand that you would like to delete the additional OpenSearch domains present. In order to check what domain is currently being utilized we will need to check the Cloudformation outputs in the AWS console. The stack would appear as a nested stack with the stack name containing the App name, environment name and `SearchableStack` present. On traversing into the outputs section we will be able to see the OpenSearchDomainArn and OpenSearchDomainEndpoint parameters present. Please make a note of the domain names in the CloudFormation stack and then delete the OpenSearch instances not being utilized.

additionally, could you please check the searchable CloudFormation stack for any any drifts

**Comment by ykethan** [comment]
Closing the issue due to inactivity. Please do reach out to us again.
