### ISSUE TITLE
Impossible to create a manyToMany circular reference on GraphQL

### ISSUE THREAD

**Issue by JonatasFischer** [aws-amplify/amplify-category-api#728]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

yarn

### If applicable, what version of Node.js are you using?

16

### Amplify CLI Version

9.2.1

### What operating system are you using?

windows

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

api

### Amplify Commands

push

### Describe the bug

There is no way to make a circular manyToMany relationship in a table.
The following error message is presented when I try to do it:
@manyToMany relation 'SubjectContentRequirements' must be used in exactly two locations.

### Expected behavior

A table called SubjectRequirements should have been created

### Reproduction steps

create a project using amplify
add the api
update the schema.graphql file with the provided schema
execute amplify push

### GraphQL schema(s)

<details>

```graphql
type Subject @model @auth(rules: [{allow: public}])  {
    id: ID! @primaryKey
    title: String

    Requires: [Subject] @manyToMany(relationName: "SubjectRequirements")
    Required: [Subject] @manyToMany(relationName: "SubjectRequirements")
}


```

</details>

### Log output

<details>

```
# Put your logs below this line
🛑 An error occurred during the push operation: /
@manyToMany relation 'SubjectContentRequirements' must be used in exactly two locations.
⚠️ Review the Amplify CLI troubleshooting guide for potential next steps: https://docs.amplify.aws/cli/project/troubleshooting/
PS C:\source\project\app\myApp> amplify version



```

</details>

**Comment by alharris-at** [comment]
Hi @JonatasFischer - thank you for reaching out. It looks like the primary reason this is failing today is because the dual `manyToMany` directives are unwrapping to identical GSIs and queries defined in the generated output, causing a collision. I think you can model this in a more manual way by explicitly defining the join table that you'll be using to connect your various models (which is effectively just a separate model that has indexes on the relevant source ids for easy queryability).

I haven't tested the below end to end, but I think you can achieve a similar outcome w/ a schema something like this.

```graphql
type Subject @model @auth(rules: [{allow: public}])  {
    id: ID!
    title: String
    requires: [SubjectRequirements] @hasMany(indexName: "byRequires", fields: ["id"])
    required: [SubjectRequirements] @hasMany(indexName: "byRequired", fields: ["id"])
}

type SubjectRequirements @model @auth(rules: [{allow: public}]) {
  id: ID!
  requiresID: ID! @index(name: "byRequires")
  requires: Subject @belongsTo(fields: ["requiresID"])
  requiredID: ID! @index(name: "byRequired")
  required: Subject @belongsTo(fields: ["requiredID"])
}
```

It's worth noting however, that if you're planning to use `Datastore` https://docs.amplify.aws/lib/datastore/getting-started/q/platform/js/ then you'll probably want to avoid cyclical relationships in general, because although we can generate apis with cycles in them with AppSync, local database constraints in Datastore mean initialization of the local database will likely fail.

**Comment by ykethan** [comment]
Hello @JonatasFischer, following up on the suggestion provided by @alharris-at. Please do let us know if you require any assistance on this.
