### ISSUE TITLE
VTL issue when field starts with an underscore: Mapping Template Lexical error,   Encountered: "_" 

### ISSUE THREAD

**Issue by conorw** [aws-amplify/amplify-category-api#735]
### Before opening, please confirm:

- [X] I have installed the latest version of the Amplify CLI (see above), and confirmed that the issue still persists.
- [X] I have [searched for duplicate or closed issues](https://github.com/aws-amplify/amplify-cli/issues?q=is%3Aissue+).
- [X] I have read the guide for [submitting bug reports](https://github.com/aws-amplify/amplify-cli/blob/dev/CONTRIBUTING.md#bug-reports).
- [X] I have done my best to include a minimal, self-contained set of instructions for consistently reproducing the issue.
- [X] I have removed any sensitive information from my code snippets and submission.

### How did you install the Amplify CLI?

npm

### If applicable, what version of Node.js are you using?

14.19.1

### Amplify CLI Version

9.2.1

### What operating system are you using?

Windows 11

### Did you make any manual changes to the cloud resources managed by Amplify? Please describe the changes made.

No manual changes made

### Amplify Categories

auth, api

### Amplify Commands

push

### Describe the bug

If the API schema contains a field starting with an underscore "_" AND field level permissions have been set in the type, the property cannot be returned in mutations or queries. 

For example: 

```
type Company
  @auth(
    rules: [
      # api key users can read only
      { allow: public, operations: [read] }
      # logged in users can read and create
      { allow: private, operations: [read, create] }
      # Only allow users of company group to edit
      { allow: groups, groupsField: "id" }
    ]
  ) {
  id: ID!
  _geoloc: GeoLocation
subscriptionPlan: String
    @auth(
      rules: [
        { allow: private, operations: [read] }
        { allow: private, provider: iam }
        { allow: groups, groups: ["Admin"] }
      ]
    )
}
```

If the create company mutation is called, the following error occurs:

"errors":[{"path":["createCompany","_geoloc"],"data":null,"errorType":"MappingTemplate","errorInfo":null,"locations":[{"line":20,"column":5,"sourceName":null}],"message":"Lexical error,   Encountered: \"_\" (95), after : \".\" at *unset*[line 10, column 31]"}]}

### Expected behavior

Graphql schema fields should be allowed to begin with an underscore.

### Reproduction steps

1. Create a schema with the following type:
```
type Company
  @auth(
    rules: [
      # api key users can read only
      { allow: public, operations: [read] }
      # logged in users can read and create
      { allow: private, operations: [read, create] }
      # Only allow users of company group to edit
      { allow: groups, groupsField: "id" }
    ]
  ) {
  id: ID!
  _geoloc: GeoLocation
subscriptionPlan: String
    @auth(
      rules: [
        { allow: private, operations: [read] }
        { allow: private, provider: iam }
        { allow: groups, groups: ["Admin"] }
      ]
    )
}
```
2. Call the createCompany mutation, making sure to return the _geoloc field e.g. 

```
createCompany = /* GraphQL */ `
  mutation CreateCompany(
    $input: CreateCompanyInput!
    $condition: ModelCompanyConditionInput
  ) {
    createCompany(input: $input, condition: $condition) {
      id
      _geoloc {
        lat
        lng
      }
      subscriptionPlan
    }
  }
`
```

### GraphQL schema(s)

<details>

```graphql
# Put schemas below this line
type Company
  @auth(
    rules: [
      # api key users can read only
      { allow: public, operations: [read] }
      # logged in users can read and create
      { allow: private, operations: [read, create] }
      # Only allow users of company group to edit
      { allow: groups, groupsField: "id" }
    ]
  ) {
  id: ID!
  _geoloc: GeoLocation
subscriptionPlan: String
    @auth(
      rules: [
        { allow: private, operations: [read] }
        { allow: private, provider: iam }
        { allow: groups, groups: ["Admin"] }
      ]
    )
}

type GeoLocation {
  lat: Float!
  lng: Float!
}
```

</details>

### Log output

<details>

```
# Put your logs below this line


```

</details>

**Comment by ncarvajalc** [comment]
# Findings
## File causing the problem
In the project folder:
`amplify/backend/api/{your_project_name}/build/resolvers/Company._geoloc.res.vtl`
```vtl
## [Start] Checking for allowed operations which can return this field. **
#set( $operation = $util.defaultIfNull($ctx.source.get("__operation"), null) )
#if( $operation == "Mutation" )
  $util.toJson(null)
#else
  $util.toJson($context.source._geoloc) ## This is the problematic field as this is not valid syntax in vtl.
#end
## [End] Checking for allowed operations which can return this field. **
```
Notice that `source._geolog_` is not valid in VTL, that is why the error is being raised in AppSync.
## Why is that resolver being generated?
The resolver is being generated in the following file:
`packages/amplify-graphql-auth-transformer/src/resolvers/field.ts`
https://github.com/aws-amplify/amplify-category-api/blob/a928809a55600da10433b0af378be093ccf609f5/packages/amplify-graphql-auth-transformer/src/resolvers/field.ts#L175-L188
Notice that the resolvers are generated using `context.source.${fieldName}`, which is causing the issue. This function is being called in the following file:
`packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts`
https://github.com/aws-amplify/amplify-category-api/blob/a928809a55600da10433b0af378be093ccf609f5/packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts#L793
By the following function:
https://github.com/aws-amplify/amplify-category-api/blob/a928809a55600da10433b0af378be093ccf609f5/packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts#L749-L764
The `protectFieldResolver` is called in:
https://github.com/aws-amplify/amplify-category-api/blob/a928809a55600da10433b0af378be093ccf609f5/packages/amplify-graphql-auth-transformer/src/graphql-auth-transformer.ts#L361-L373
Notice that its execution depends on `needsFieldResolver` being true, which happens when `allowedRoles.length < fieldReadRoles.length`. This is happening due to the use of Field-level authorization rules and security reasons mentioned in the [Field-level authorization documentation](https://docs.amplify.aws/cli/graphql/authorization-rules/#field-level-authorization-rules):
>To prevent sensitive data from being sent over subscriptions, the GraphQL Transformer needs to alter the response of mutations for those fields by setting them to null. Therefore, to facilitate field-level authorization with subscriptions, you need to either apply field-level authorization rules to all **required** fields, make the other fields nullable, or disable subscriptions by setting it to public or off.

I will send a pull request to fix the issue.

In the mean time, to temporarily fix your issue I would recommend modifying the resolver function uploaded to AppSync to the following:
```vtl
## [Start] Checking for allowed operations which can return this field. **
#set( $operation = $util.defaultIfNull($ctx.source.get("__operation"), null) )
#if( $operation == "Mutation" )
  $util.toJson(null)
#else
  $util.toJson($context.source["_geoloc"])
#end
## [End] Checking for allowed operations which can return this field. **
```
Notice how `source._geoloc` was changed to `source["_geoloc"]`.

To modify the resolver function you should go to your Amplify console and select the project and environment you are working in.
Once there go to **API** and click in **View in AppSync**:
![[Pasted image 20221111150541.png]]
Go to **Functions** and click the **Company_geolocDataResolverFn**:
![[Pasted image 20221111150728.png]]
Scroll down to **Configure the response mapping template.**, paste the new resolver function and click in the **Save function** button.

The `MappingTemplate` error should now disappear and let you create your Company model. Notice that now ` "_geoloc": null,` will be retrieved in any mutation response because of the restrictions of using field-level authorization mentioned above, but it should work fine with query responses:

Create company response:
```json
{
  "data": {
    "createCompany": {
      "_geoloc": null,
      "createdAt": "2022-11-11T20:13:14.768Z"
    }
  }
}
```

List companies response:
```json
{
  "data": {
    "listCompanies": {
      "items": [
        {
          "id": "e228e31d-d94d-434e-996d-606293b3534d",
          "_geoloc": {
            "lng": 1.5,
            "lat": 1.5
          }
        },
        {
          "id": "9bd88295-2dd4-4971-bbaf-f531bf0c86fa",
          "_geoloc": {
            "lng": 1.5,
            "lat": 1.5
          }
        },
    ...
    ]
  }
}
```
